
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
# https://github.com/Huachao/vscode-restclient

@host = 10.200.30.111:3000



############################     -- Login User - Ben
# @name userLogin
POST http://{{host}}/users/login
Content-Type: application/json

{
    "email": "bunookana@gmail.com",
    "password": "cami223!"
}


############################     -- Login User - Cami
# @name userLogin
POST http://{{host}}/users/login
Content-Type: application/json

{
    "email": "perky@example.com",
    "password": "ben223!"
}

############################     -- Create user Cami
# @name userLogin
POST http://{{host}}/users
Content-Type: application/json

{
    "name": "Cami Gordon",
    "email": "perky@example.com",
    "password": "ben223!"
}

############################     -- Create user Marli
# @name userLogin
POST http://{{host}}/users
Content-Type: application/json

{
    "name": "Marli Gordon",
    "email": "marly@example.com",
    "password": "hemi223!"
}


############################     -- Create user Ben
# @name userLogin
POST http://{{host}}/users
Content-Type: application/json

{
    "name": "Ben Gordon",
    "email": "bunookana@gmail.com",
    "password": "cami223!"
}


############################     -- Show user self details
GET http://{{host}}/users/me
Content-Type: application/json
Authorization: Bearer {{userLogin.response.body.token}}


############################     -- Logout user
POST  http://{{host}}/users/logout
Content-Type: application/json
Authorization: Bearer {{userLogin.response.body.token}}


############################     -- Logout user - All Sessions
POST  http://{{host}}/users/logoutAll
Content-Type: application/json
Authorization: Bearer {{userLogin.response.body.token}}


############################     -- Update user
PATCH http://{{host}}/users/me
Content-Type: application/json
Authorization: Bearer {{userLogin.response.body.token}}

# --- broken update
# {
#     "weapon": "screwdriver"
# }

# --- good update
{
    "name": "Awesome Guy",
    "age": 35,
    "password": "newpiss!@#$"
}

############################     -- Delete user self
DELETE  http://{{host}}/users/me
Content-Type: application/json
Authorization: Bearer {{userLogin.response.body.token}}












############################     --Create task 1
POST http://{{host}}/tasks
Content-Type: application/json
Authorization: Bearer {{userLogin.response.body.token}}

{
    "description": "first",
    "completed": true
}


############################     --Create task 2
POST http://{{host}}/tasks
Content-Type: application/json
Authorization: Bearer {{userLogin.response.body.token}}

{
    "description": "second",
    "completed": false
}


############################     --Create task 3
POST http://{{host}}/tasks
Content-Type: application/json
Authorization: Bearer {{userLogin.response.body.token}}

{
    "description": "third",
    "completed": true
}


############################     --Create task 4
POST http://{{host}}/tasks
Content-Type: application/json
Authorization: Bearer {{userLogin.response.body.token}}

{
    "description": "fourth"
}

############################     --Create task 5
POST http://{{host}}/tasks
Content-Type: application/json
Authorization: Bearer {{userLogin.response.body.token}}

{
    "description": "fifth"
}

############################     -- List tasks
GET http://{{host}}/tasks
#?limit=2&skip=4
?sortBy=createdAt:desc
?sortBy=createdAt:asc
Content-Type: application/json
Authorization: Bearer {{userLogin.response.body.token}}


############################     -- List NOT completed tasks
GET http://{{host}}/tasks?completed=false
Content-Type: application/json
Authorization: Bearer {{userLogin.response.body.token}}


############################     -- List completed tasks
GET http://{{host}}/tasks?completed=true
Content-Type: application/json
Authorization: Bearer {{userLogin.response.body.token}}

############################     -- Get task by id
GET http://{{host}}/tasks/5e7b79b582790d498ac4a4c7
Content-Type: application/json
Authorization: Bearer {{userLogin.response.body.token}}

############################     -- Delete task by id
DELETE  http://{{host}}/tasks/5e7b997bb320cd4c9ac6dc4a
Content-Type: application/json
Authorization: Bearer {{userLogin.response.body.token}}


############################     -- Update task by id
PATCH  http://{{host}}/tasks/5e7b9982b320cd4c9ac6dc4c
Content-Type: application/json
Authorization: Bearer {{userLogin.response.body.token}}

{
    "completed": "true"
}

# {
#     "description": "new description"
# }